select*
from customer;

--total revenue generated by male vs female customers
select gender,sum(purchase_amount) as revenue
from customer
group by gender;

-- customer used discount but still spent more than average purchase amount
select customer_id,purchase_amount
from customer
where discount_applied='Yes' AND purchase_amount >= (select AVG(purchase_amount) from customer);

--top 5 product with highest average review
select column_name
from information_schema.columns
where table_name='customer';

select item_purchased,round(avg(review_rating::numeric),2) as average_product_rating
from customer
group by item_purchased
order by avg(review_rating) desc 
limit 5;

--average purchase amount between standard and express shipping comparison
select shipping_type, round(avg(purchase_amount),2) as  avg_purchase_amount
from customer
group by shipping_type
having shipping_type in('Standard','Express');

-- comparison between the total and average revenue among subscribed and non-subscribed customers
select subscription_status,
round(avg(purchase_amount),2) as avg_revenue,
sum(purchase_amount) as total_revenue,count(purchase_amount) as no_purchases
from customer
group by subscription_status ;

-- 5 products with highest percentage of purchase with discount applied
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_applied_percentage
from customer 
group by item_purchased
order by discount_applied_percentage desc
limit 5 ;

--segment customer into New,Returning, Loyal based on previous purchase and show the count on each segment
with customer_type as 
(
select customer_id,previous_purchases,
(case when previous_purchases=1 then 'New customer'
     when previous_purchases between 2 and 10 then 'Returning customer'
	 else 'Loyal customer' end ) as customer_segment
from customer
)
select customer_segment,count(*) as no_customers
from customer_type
group by customer_segment;

--top 3 most purchased items from each category
with item_count as
(
select category,item_purchased,count(customer_id) as no_purchase,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from customer
group by category,item_purchased
) 
select item_rank,category,item_purchased,no_purchase
from item_count
where item_rank<=3 ;

--are repeat buyers(more than 5 previous purchases) likey to subscribe
select subscription_status,count(customer_id) no_customer
from customer
where previous_purchases>5
group by subscription_status;

select column_name
from information_schema.columns
where table_name='customer';

--revenue contribution of each age group
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;


